services:
  ekko-postgres:
    image: postgres:16
    container_name: ekko_pg_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ekkochat
    ports:
      - "5432:5432"
    volumes:
      - ekko_vol_pg:/var/lib/postgresql/data
    networks:
      - ekko-network
  ekko-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ekko_pgadmin_dev
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadminpassword
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - ekko_vol_pgadmin:/var/lib/pgadmin
    networks:
      - ekko-network

networks:
  ekko-network:
    driver: bridge

volumes:
  ekko_vol_pg:
  ekko_vol_pgadmin: