spring:
  application:
    name: ekkochatsrv
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ekkochat
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  main:
    banner-mode: off

logging:
  level:
    root: warn
    com:
      cdcrane:
        ekkochatsrv: info

jwt:
  access_jwt_secret: SuperSecretAccessJwtEncryptionKeyYouShouldOverwriteWithEnvVariables
  refresh_jwt_secret: SuperSecretRefreshJwtEncryptionKeyYouShouldOverwriteWithEnvVariables
  issuer: EkkoChatSRV
  refresh_expiration: 432000000 # 5d only for the refresh token
  access_expiration: 300000 # 5m only for access token

cors:
  allowed-origins: http://localhost:4200 # Overwrite with env variables