spring:
  application:
    name: ekkochatsrv
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ekkochat
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  main:
    banner-mode: off

logging:
  level:
    root: warn
    com:
      cdcrane:
        ekkochatsrv: info

jwt:
  secret: SuperSecretJwtEncryptionKeyYouShouldOverwriteWithEnvVariables
  issuer: EkkoChatSRV
  expiration: 28800000 # 8h